// Code generated by "stringer -type=DarwinOptsScope -linecomment"; DO NOT EDIT.

package crontab

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[darwinNoScope-0]
	_ = x[UserScope-1]
	_ = x[SystemScope-2]
	_ = x[DarwinDaemonSystemScope-3]
}

const _DarwinOptsScope_name = "UnspecifiedUserSystemDaemon system"

var _DarwinOptsScope_index = [...]uint8{0, 11, 15, 21, 34}

func (i DarwinOptsScope) String() string {
	if i >= DarwinOptsScope(len(_DarwinOptsScope_index)-1) {
		return "DarwinOptsScope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DarwinOptsScope_name[_DarwinOptsScope_index[i]:_DarwinOptsScope_index[i+1]]
}
