// Code generated by "stringer -type=Scope -trimprefix=Scope -output options_scope_stringer.go"; DO NOT EDIT.

package god

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScopeUser-0]
	_ = x[ScopeSystem-1]
}

const _Scope_name = "UserSystem"

var _Scope_index = [...]uint8{0, 4, 10}

func (i Scope) String() string {
	if i >= Scope(len(_Scope_index)-1) {
		return "Scope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Scope_name[_Scope_index[i]:_Scope_index[i+1]]
}
