// Code generated by "stringer -type=State -trimprefix=State -output options_state_stringer.go"; DO NOT EDIT.

package god

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateEnable-0]
	_ = x[StateDisable-1]
}

const _State_name = "EnableDisable"

var _State_index = [...]uint8{0, 6, 13}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
