// Code generated by "stringer -type=DarwinLimitLoadToSessionType -trimprefix=DarwinLimitLoadToSession -output options_darwin_limitloadtosession_stringer.go"; DO NOT EDIT.

package god

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DarwinLimitLoadToSessionAqua-0]
	_ = x[DarwinLimitLoadToSessionStandardIO-1]
	_ = x[DarwinLimitLoadToSessionBackground-2]
	_ = x[DarwinLimitLoadToSessionLoginWindow-3]
}

const _DarwinLimitLoadToSessionType_name = "AquaStandardIOBackgroundLoginWindow"

var _DarwinLimitLoadToSessionType_index = [...]uint8{0, 4, 14, 24, 35}

func (i DarwinLimitLoadToSessionType) String() string {
	if i >= DarwinLimitLoadToSessionType(len(_DarwinLimitLoadToSessionType_index)-1) {
		return "DarwinLimitLoadToSessionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DarwinLimitLoadToSessionType_name[_DarwinLimitLoadToSessionType_index[i]:_DarwinLimitLoadToSessionType_index[i+1]]
}
