// Code generated by "stringer -type=OptionKey -linecomment"; DO NOT EDIT.

package god

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Name-0]
	_ = x[Type-1]
	_ = x[State-2]
	_ = x[Description-3]
	_ = x[Program-4]
	_ = x[ProgramArguments-5]
	_ = x[Envs-6]
	_ = x[Scope-7]
	_ = x[Interval-8]
}

const _OptionKey_name = "NameTypeStateDescriptionProgramProgramArgumentsEnvsScopeInterval"

var _OptionKey_index = [...]uint8{0, 4, 8, 13, 24, 31, 47, 51, 56, 64}

func (i OptionKey) String() string {
	if i >= OptionKey(len(_OptionKey_index)-1) {
		return "OptionKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OptionKey_name[_OptionKey_index[i]:_OptionKey_index[i+1]]
}
