// Code generated by "stringer -type=Scope -linecomment"; DO NOT EDIT.

package god

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[scopeUnspecified-0]
	_ = x[ScopeUser-1]
	_ = x[ScopeSystem-2]
}

const _Scope_name = "unspecifiedusersystem"

var _Scope_index = [...]uint8{0, 11, 15, 21}

func (i Scope) String() string {
	if i >= Scope(len(_Scope_index)-1) {
		return "Scope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Scope_name[_Scope_index[i]:_Scope_index[i+1]]
}
