// Code generated by "stringer -type=UnitScope -linecomment"; DO NOT EDIT.

package god

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[scopeUnspecified-0]
	_ = x[ScopeUser-1]
	_ = x[ScopeSystem-2]
}

const _UnitScope_name = "unspecifiedusersystem"

var _UnitScope_index = [...]uint8{0, 11, 15, 21}

func (i UnitScope) String() string {
	if i >= UnitScope(len(_UnitScope_index)-1) {
		return "UnitScope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnitScope_name[_UnitScope_index[i]:_UnitScope_index[i+1]]
}
